[package]
name = "bevy_animation_graph"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.12.0"
bevy_xpbd_3d = "0.3.1"
bevy_egui_editor = { git = "https://github.com/mbrea-c/bevy_egui_editor.git" }
thiserror = "1.0.50"
ron = "0.8.1"
serde = { version = "1.0.193", features = ["derive"] }
